package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bodega generated by hbm2java
 */
@Entity
@Table(name = "bodega", catalog = "lapalmera")
public class Bodega implements java.io.Serializable {

	private String codigo;
	private String nombre;
	private Set<Ubicacion> ubicacions = new HashSet<Ubicacion>(0);

	public Bodega() {
	}

	public Bodega(String codigo) {
		this.codigo = codigo;
	}

	public Bodega(String codigo, String nombre, Set<Ubicacion> ubicacions) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.ubicacions = ubicacions;
	}

	@Id
	@Column(name = "CODIGO", unique = true, nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "NOMBRE", length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bodega")
	public Set<Ubicacion> getUbicacions() {
		return this.ubicacions;
	}

	public void setUbicacions(Set<Ubicacion> ubicacions) {
		this.ubicacions = ubicacions;
	}

}
