package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Capturaproduccion generated by hbm2java
 */
@Entity
@Table(name = "capturaproduccion", catalog = "lapalmera")
public class Capturaproduccion implements java.io.Serializable {

	private Integer correlativoproduccion;
	private Unidadmedida unidadmedida;
	private Producto producto;
	private Programaproduccion programaproduccion;
	private Date fechacapturaproduccion;
	private Float cantidadproduccion;
	private String observacion;
	private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);

	public Capturaproduccion() {
	}

	public Capturaproduccion(Unidadmedida unidadmedida, Producto producto,
			Date fechacapturaproduccion) {
		this.unidadmedida = unidadmedida;
		this.producto = producto;
		this.fechacapturaproduccion = fechacapturaproduccion;
	}

	public Capturaproduccion(Unidadmedida unidadmedida, Producto producto,
			Programaproduccion programaproduccion, Date fechacapturaproduccion,
			Float cantidadproduccion, String observacion,
			Set<Funcionario> funcionarios) {
		this.unidadmedida = unidadmedida;
		this.producto = producto;
		this.programaproduccion = programaproduccion;
		this.fechacapturaproduccion = fechacapturaproduccion;
		this.cantidadproduccion = cantidadproduccion;
		this.observacion = observacion;
		this.funcionarios = funcionarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CORRELATIVOPRODUCCION", unique = true, nullable = false)
	public Integer getCorrelativoproduccion() {
		return this.correlativoproduccion;
	}

	public void setCorrelativoproduccion(Integer correlativoproduccion) {
		this.correlativoproduccion = correlativoproduccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOUNIDADMEDIDA", nullable = false)
	public Unidadmedida getUnidadmedida() {
		return this.unidadmedida;
	}

	public void setUnidadmedida(Unidadmedida unidadmedida) {
		this.unidadmedida = unidadmedida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOPRODUCTO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOPROGRAMAPRODUCCION")
	public Programaproduccion getProgramaproduccion() {
		return this.programaproduccion;
	}

	public void setProgramaproduccion(Programaproduccion programaproduccion) {
		this.programaproduccion = programaproduccion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHACAPTURAPRODUCCION", nullable = false, length = 19)
	public Date getFechacapturaproduccion() {
		return this.fechacapturaproduccion;
	}

	public void setFechacapturaproduccion(Date fechacapturaproduccion) {
		this.fechacapturaproduccion = fechacapturaproduccion;
	}

	@Column(name = "CANTIDADPRODUCCION", precision = 12, scale = 0)
	public Float getCantidadproduccion() {
		return this.cantidadproduccion;
	}

	public void setCantidadproduccion(Float cantidadproduccion) {
		this.cantidadproduccion = cantidadproduccion;
	}

	@Column(name = "OBSERVACION", length = 80)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "produccionfuncionario", catalog = "lapalmera", joinColumns = { @JoinColumn(name = "CORRELATIVOPRODUCCION", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "RUTFUNCIONARIO", nullable = false, updatable = false) })
	public Set<Funcionario> getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Set<Funcionario> funcionarios) {
		this.funcionarios = funcionarios;
	}

}
