package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Conceptotecnico generated by hbm2java
 */
@Entity
@Table(name = "conceptotecnico", catalog = "lapalmera")
public class Conceptotecnico implements java.io.Serializable {

	private String codigoconceptotecnico;
	private String nombreconceptotecnico;
	private Set<Fichatecnica> fichatecnicas = new HashSet<Fichatecnica>(0);

	public Conceptotecnico() {
	}

	public Conceptotecnico(String codigoconceptotecnico) {
		this.codigoconceptotecnico = codigoconceptotecnico;
	}

	public Conceptotecnico(String codigoconceptotecnico,
			String nombreconceptotecnico, Set<Fichatecnica> fichatecnicas) {
		this.codigoconceptotecnico = codigoconceptotecnico;
		this.nombreconceptotecnico = nombreconceptotecnico;
		this.fichatecnicas = fichatecnicas;
	}

	@Id
	@Column(name = "CODIGOCONCEPTOTECNICO", unique = true, nullable = false, length = 20)
	public String getCodigoconceptotecnico() {
		return this.codigoconceptotecnico;
	}

	public void setCodigoconceptotecnico(String codigoconceptotecnico) {
		this.codigoconceptotecnico = codigoconceptotecnico;
	}

	@Column(name = "NOMBRECONCEPTOTECNICO", length = 80)
	public String getNombreconceptotecnico() {
		return this.nombreconceptotecnico;
	}

	public void setNombreconceptotecnico(String nombreconceptotecnico) {
		this.nombreconceptotecnico = nombreconceptotecnico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conceptotecnico")
	public Set<Fichatecnica> getFichatecnicas() {
		return this.fichatecnicas;
	}

	public void setFichatecnicas(Set<Fichatecnica> fichatecnicas) {
		this.fichatecnicas = fichatecnicas;
	}

}
