package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Confirmacionpedido generated by hbm2java
 */
@Entity
@Table(name = "confirmacionpedido", catalog = "lapalmera")
public class Confirmacionpedido implements java.io.Serializable {

	private int numeropedido;
	private Pedido pedido;
	private String nombrecliente;
	private String apellidocliente;
	private String direccioncliente;
	private Date fecha;

	public Confirmacionpedido() {
	}

	public Confirmacionpedido(Pedido pedido, Date fecha) {
		this.pedido = pedido;
		this.fecha = fecha;
	}

	public Confirmacionpedido(Pedido pedido, String nombrecliente,
			String apellidocliente, String direccioncliente, Date fecha) {
		this.pedido = pedido;
		this.nombrecliente = nombrecliente;
		this.apellidocliente = apellidocliente;
		this.direccioncliente = direccioncliente;
		this.fecha = fecha;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pedido"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "NUMEROPEDIDO", unique = true, nullable = false)
	public int getNumeropedido() {
		return this.numeropedido;
	}

	public void setNumeropedido(int numeropedido) {
		this.numeropedido = numeropedido;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@Column(name = "NOMBRECLIENTE", length = 80)
	public String getNombrecliente() {
		return this.nombrecliente;
	}

	public void setNombrecliente(String nombrecliente) {
		this.nombrecliente = nombrecliente;
	}

	@Column(name = "APELLIDOCLIENTE", length = 80)
	public String getApellidocliente() {
		return this.apellidocliente;
	}

	public void setApellidocliente(String apellidocliente) {
		this.apellidocliente = apellidocliente;
	}

	@Column(name = "DIRECCIONCLIENTE", length = 80)
	public String getDireccioncliente() {
		return this.direccioncliente;
	}

	public void setDireccioncliente(String direccioncliente) {
		this.direccioncliente = direccioncliente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
