package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Despachopedido generated by hbm2java
 */
@Entity
@Table(name = "despachopedido", catalog = "lapalmera")
public class Despachopedido implements java.io.Serializable {

	private int numeropedido;
	private Pedido pedido;
	private Entrega entrega;
	private String nombrecliente;
	private Date fechaentregadespacho;

	public Despachopedido() {
	}

	public Despachopedido(Pedido pedido, Entrega entrega, String nombrecliente,
			Date fechaentregadespacho) {
		this.pedido = pedido;
		this.entrega = entrega;
		this.nombrecliente = nombrecliente;
		this.fechaentregadespacho = fechaentregadespacho;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pedido"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "NUMEROPEDIDO", unique = true, nullable = false)
	public int getNumeropedido() {
		return this.numeropedido;
	}

	public void setNumeropedido(int numeropedido) {
		this.numeropedido = numeropedido;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOENTREGA", nullable = false)
	public Entrega getEntrega() {
		return this.entrega;
	}

	public void setEntrega(Entrega entrega) {
		this.entrega = entrega;
	}

	@Column(name = "NOMBRECLIENTE", nullable = false, length = 80)
	public String getNombrecliente() {
		return this.nombrecliente;
	}

	public void setNombrecliente(String nombrecliente) {
		this.nombrecliente = nombrecliente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAENTREGADESPACHO", nullable = false, length = 19)
	public Date getFechaentregadespacho() {
		return this.fechaentregadespacho;
	}

	public void setFechaentregadespacho(Date fechaentregadespacho) {
		this.fechaentregadespacho = fechaentregadespacho;
	}

}
