package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Detalleentregainsumo generated by hbm2java
 */
@Entity
@Table(name = "detalleentregainsumo", catalog = "lapalmera")
public class Detalleentregainsumo implements java.io.Serializable {

	private int correlativoentregainsumo;
	private Unidadmedida unidadmedida;
	private Entregainsumo entregainsumo;
	private Producto producto;
	private Integer cantidadentregainsumo;

	public Detalleentregainsumo() {
	}

	public Detalleentregainsumo(Unidadmedida unidadmedida,
			Entregainsumo entregainsumo, Producto producto) {
		this.unidadmedida = unidadmedida;
		this.entregainsumo = entregainsumo;
		this.producto = producto;
	}

	public Detalleentregainsumo(Unidadmedida unidadmedida,
			Entregainsumo entregainsumo, Producto producto,
			Integer cantidadentregainsumo) {
		this.unidadmedida = unidadmedida;
		this.entregainsumo = entregainsumo;
		this.producto = producto;
		this.cantidadentregainsumo = cantidadentregainsumo;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "entregainsumo"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CORRELATIVOENTREGAINSUMO", unique = true, nullable = false)
	public int getCorrelativoentregainsumo() {
		return this.correlativoentregainsumo;
	}

	public void setCorrelativoentregainsumo(int correlativoentregainsumo) {
		this.correlativoentregainsumo = correlativoentregainsumo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOUNIDADMEDIDA", nullable = false)
	public Unidadmedida getUnidadmedida() {
		return this.unidadmedida;
	}

	public void setUnidadmedida(Unidadmedida unidadmedida) {
		this.unidadmedida = unidadmedida;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Entregainsumo getEntregainsumo() {
		return this.entregainsumo;
	}

	public void setEntregainsumo(Entregainsumo entregainsumo) {
		this.entregainsumo = entregainsumo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOINSUMO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "CANTIDADENTREGAINSUMO")
	public Integer getCantidadentregainsumo() {
		return this.cantidadentregainsumo;
	}

	public void setCantidadentregainsumo(Integer cantidadentregainsumo) {
		this.cantidadentregainsumo = cantidadentregainsumo;
	}

}
