package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallepedido generated by hbm2java
 */
@Entity
@Table(name = "detallepedido", catalog = "lapalmera")
public class Detallepedido implements java.io.Serializable {

	private Integer correlativo;
	private Pedido pedido;
	private Producto producto;
	private int precioproducto;
	private int cantidadproducto;
	private String observacion;
	private byte active;

	public Detallepedido() {
	}

	public Detallepedido(Pedido pedido, Producto producto, int precioproducto,
			int cantidadproducto, byte active) {
		this.pedido = pedido;
		this.producto = producto;
		this.precioproducto = precioproducto;
		this.cantidadproducto = cantidadproducto;
		this.active = active;
	}

	public Detallepedido(Pedido pedido, Producto producto, int precioproducto,
			int cantidadproducto, String observacion, byte active) {
		this.pedido = pedido;
		this.producto = producto;
		this.precioproducto = precioproducto;
		this.cantidadproducto = cantidadproducto;
		this.observacion = observacion;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CORRELATIVO", unique = true, nullable = false)
	public Integer getCorrelativo() {
		return this.correlativo;
	}

	public void setCorrelativo(Integer correlativo) {
		this.correlativo = correlativo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUMEROPEDIDO", nullable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOPRODUCTO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "PRECIOPRODUCTO", nullable = false)
	public int getPrecioproducto() {
		return this.precioproducto;
	}

	public void setPrecioproducto(int precioproducto) {
		this.precioproducto = precioproducto;
	}

	@Column(name = "CANTIDADPRODUCTO", nullable = false)
	public int getCantidadproducto() {
		return this.cantidadproducto;
	}

	public void setCantidadproducto(int cantidadproducto) {
		this.cantidadproducto = cantidadproducto;
	}

	@Column(name = "OBSERVACION", length = 45)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "ACTIVE", nullable = false)
	public byte getActive() {
		return this.active;
	}

	public void setActive(byte active) {
		this.active = active;
	}

}
