package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Detalledevolucioninsumo generated by hbm2java
 */
@Entity
@Table(name = "detalledevolucioninsumo", catalog = "lapalmera")
public class Detalledevolucioninsumo implements java.io.Serializable {

	private int correlativodevolucioninsumo;
	private Devolucioninsumo devolucioninsumo;
	private Producto producto;
	private Integer cantidaddevolucioninsumo;
	private String codigounidadmedida;

	public Detalledevolucioninsumo() {
	}

	public Detalledevolucioninsumo(Devolucioninsumo devolucioninsumo,
			Producto producto, String codigounidadmedida) {
		this.devolucioninsumo = devolucioninsumo;
		this.producto = producto;
		this.codigounidadmedida = codigounidadmedida;
	}

	public Detalledevolucioninsumo(Devolucioninsumo devolucioninsumo,
			Producto producto, Integer cantidaddevolucioninsumo,
			String codigounidadmedida) {
		this.devolucioninsumo = devolucioninsumo;
		this.producto = producto;
		this.cantidaddevolucioninsumo = cantidaddevolucioninsumo;
		this.codigounidadmedida = codigounidadmedida;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "devolucioninsumo"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CORRELATIVODEVOLUCIONINSUMO", unique = true, nullable = false)
	public int getCorrelativodevolucioninsumo() {
		return this.correlativodevolucioninsumo;
	}

	public void setCorrelativodevolucioninsumo(int correlativodevolucioninsumo) {
		this.correlativodevolucioninsumo = correlativodevolucioninsumo;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Devolucioninsumo getDevolucioninsumo() {
		return this.devolucioninsumo;
	}

	public void setDevolucioninsumo(Devolucioninsumo devolucioninsumo) {
		this.devolucioninsumo = devolucioninsumo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOINSUMO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "CANTIDADDEVOLUCIONINSUMO")
	public Integer getCantidaddevolucioninsumo() {
		return this.cantidaddevolucioninsumo;
	}

	public void setCantidaddevolucioninsumo(Integer cantidaddevolucioninsumo) {
		this.cantidaddevolucioninsumo = cantidaddevolucioninsumo;
	}

	@Column(name = "CODIGOUNIDADMEDIDA", nullable = false, length = 20)
	public String getCodigounidadmedida() {
		return this.codigounidadmedida;
	}

	public void setCodigounidadmedida(String codigounidadmedida) {
		this.codigounidadmedida = codigounidadmedida;
	}

}
