package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entrega generated by hbm2java
 */
@Entity
@Table(name = "entrega", catalog = "lapalmera")
public class Entrega implements java.io.Serializable {

	private String codigo;
	private String descripcion;
	private Set<Despachopedido> despachopedidos = new HashSet<Despachopedido>(0);

	public Entrega() {
	}

	public Entrega(String codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public Entrega(String codigo, String descripcion,
			Set<Despachopedido> despachopedidos) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.despachopedidos = despachopedidos;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 1)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entrega")
	public Set<Despachopedido> getDespachopedidos() {
		return this.despachopedidos;
	}

	public void setDespachopedidos(Set<Despachopedido> despachopedidos) {
		this.despachopedidos = despachopedidos;
	}

}
