package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Especificarproduccion generated by hbm2java
 */
@Entity
@Table(name = "especificarproduccion", catalog = "lapalmera")
public class Especificarproduccion implements java.io.Serializable {

	private String codigoordenfabricacion;
	private Funcionario funcionario;
	private String codigoproducto;
	private String codigolineaproduccion;
	private Date fechaespecificarproduccion;
	private Date horaespecificarproduccion;

	public Especificarproduccion() {
	}

	public Especificarproduccion(String codigoordenfabricacion,
			String codigoproducto, Date horaespecificarproduccion) {
		this.codigoordenfabricacion = codigoordenfabricacion;
		this.codigoproducto = codigoproducto;
		this.horaespecificarproduccion = horaespecificarproduccion;
	}

	public Especificarproduccion(String codigoordenfabricacion,
			Funcionario funcionario, String codigoproducto,
			String codigolineaproduccion, Date fechaespecificarproduccion,
			Date horaespecificarproduccion) {
		this.codigoordenfabricacion = codigoordenfabricacion;
		this.funcionario = funcionario;
		this.codigoproducto = codigoproducto;
		this.codigolineaproduccion = codigolineaproduccion;
		this.fechaespecificarproduccion = fechaespecificarproduccion;
		this.horaespecificarproduccion = horaespecificarproduccion;
	}

	@Id
	@Column(name = "CODIGOORDENFABRICACION", unique = true, nullable = false, length = 20)
	public String getCodigoordenfabricacion() {
		return this.codigoordenfabricacion;
	}

	public void setCodigoordenfabricacion(String codigoordenfabricacion) {
		this.codigoordenfabricacion = codigoordenfabricacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RUTFUNCIONARIO")
	public Funcionario getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(Funcionario funcionario) {
		this.funcionario = funcionario;
	}

	@Column(name = "CODIGOPRODUCTO", nullable = false, length = 20)
	public String getCodigoproducto() {
		return this.codigoproducto;
	}

	public void setCodigoproducto(String codigoproducto) {
		this.codigoproducto = codigoproducto;
	}

	@Column(name = "CODIGOLINEAPRODUCCION", length = 20)
	public String getCodigolineaproduccion() {
		return this.codigolineaproduccion;
	}

	public void setCodigolineaproduccion(String codigolineaproduccion) {
		this.codigolineaproduccion = codigolineaproduccion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHAESPECIFICARPRODUCCION", length = 10)
	public Date getFechaespecificarproduccion() {
		return this.fechaespecificarproduccion;
	}

	public void setFechaespecificarproduccion(Date fechaespecificarproduccion) {
		this.fechaespecificarproduccion = fechaespecificarproduccion;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HORAESPECIFICARPRODUCCION", nullable = false, length = 8)
	public Date getHoraespecificarproduccion() {
		return this.horaespecificarproduccion;
	}

	public void setHoraespecificarproduccion(Date horaespecificarproduccion) {
		this.horaespecificarproduccion = horaespecificarproduccion;
	}

}
