package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadoordenfabricacion generated by hbm2java
 */
@Entity
@Table(name = "estadoordenfabricacion", catalog = "lapalmera")
public class Estadoordenfabricacion implements java.io.Serializable {

	private String codigo;
	private String nombre;
	private Set<Ordenfabricacion> ordenfabricacions = new HashSet<Ordenfabricacion>(
			0);

	public Estadoordenfabricacion() {
	}

	public Estadoordenfabricacion(String codigo) {
		this.codigo = codigo;
	}

	public Estadoordenfabricacion(String codigo, String nombre,
			Set<Ordenfabricacion> ordenfabricacions) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.ordenfabricacions = ordenfabricacions;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoordenfabricacion")
	public Set<Ordenfabricacion> getOrdenfabricacions() {
		return this.ordenfabricacions;
	}

	public void setOrdenfabricacions(Set<Ordenfabricacion> ordenfabricacions) {
		this.ordenfabricacions = ordenfabricacions;
	}

}
