package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadopedido generated by hbm2java
 */
@Entity
@Table(name = "estadopedido", catalog = "lapalmera")
public class Estadopedido implements java.io.Serializable {

	private String codigo;
	private String nombre;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Estadopedido() {
	}

	public Estadopedido(String codigo) {
		this.codigo = codigo;
	}

	public Estadopedido(String codigo, String nombre, Set<Pedido> pedidos) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.pedidos = pedidos;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadopedido")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
