package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fichatecnica generated by hbm2java
 */
@Entity
@Table(name = "fichatecnica", catalog = "lapalmera")
public class Fichatecnica implements java.io.Serializable {

	private FichatecnicaId id;
	private Producto producto;
	private Conceptotecnico conceptotecnico;
	private String descripcion;

	public Fichatecnica() {
	}

	public Fichatecnica(FichatecnicaId id, Producto producto,
			Conceptotecnico conceptotecnico) {
		this.id = id;
		this.producto = producto;
		this.conceptotecnico = conceptotecnico;
	}

	public Fichatecnica(FichatecnicaId id, Producto producto,
			Conceptotecnico conceptotecnico, String descripcion) {
		this.id = id;
		this.producto = producto;
		this.conceptotecnico = conceptotecnico;
		this.descripcion = descripcion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoproducto", column = @Column(name = "CODIGOPRODUCTO", nullable = false, length = 20)),
			@AttributeOverride(name = "codigoconceptotecnico", column = @Column(name = "CODIGOCONCEPTOTECNICO", nullable = false, length = 20)) })
	public FichatecnicaId getId() {
		return this.id;
	}

	public void setId(FichatecnicaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOPRODUCTO", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOCONCEPTOTECNICO", nullable = false, insertable = false, updatable = false)
	public Conceptotecnico getConceptotecnico() {
		return this.conceptotecnico;
	}

	public void setConceptotecnico(Conceptotecnico conceptotecnico) {
		this.conceptotecnico = conceptotecnico;
	}

	@Column(name = "DESCRIPCION", length = 80)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
