package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FichatecnicaId generated by hbm2java
 */
@Embeddable
public class FichatecnicaId implements java.io.Serializable {

	private String codigoproducto;
	private String codigoconceptotecnico;

	public FichatecnicaId() {
	}

	public FichatecnicaId(String codigoproducto, String codigoconceptotecnico) {
		this.codigoproducto = codigoproducto;
		this.codigoconceptotecnico = codigoconceptotecnico;
	}

	@Column(name = "CODIGOPRODUCTO", nullable = false, length = 20)
	public String getCodigoproducto() {
		return this.codigoproducto;
	}

	public void setCodigoproducto(String codigoproducto) {
		this.codigoproducto = codigoproducto;
	}

	@Column(name = "CODIGOCONCEPTOTECNICO", nullable = false, length = 20)
	public String getCodigoconceptotecnico() {
		return this.codigoconceptotecnico;
	}

	public void setCodigoconceptotecnico(String codigoconceptotecnico) {
		this.codigoconceptotecnico = codigoconceptotecnico;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FichatecnicaId))
			return false;
		FichatecnicaId castOther = (FichatecnicaId) other;

		return ((this.getCodigoproducto() == castOther.getCodigoproducto()) || (this
				.getCodigoproducto() != null
				&& castOther.getCodigoproducto() != null && this
				.getCodigoproducto().equals(castOther.getCodigoproducto())))
				&& ((this.getCodigoconceptotecnico() == castOther
						.getCodigoconceptotecnico()) || (this
						.getCodigoconceptotecnico() != null
						&& castOther.getCodigoconceptotecnico() != null && this
						.getCodigoconceptotecnico().equals(
								castOther.getCodigoconceptotecnico())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoproducto() == null ? 0 : this.getCodigoproducto()
						.hashCode());
		result = 37
				* result
				+ (getCodigoconceptotecnico() == null ? 0 : this
						.getCodigoconceptotecnico().hashCode());
		return result;
	}

}
