package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ingrediente generated by hbm2java
 */
@Entity
@Table(name = "ingrediente", catalog = "lapalmera")
public class Ingrediente implements java.io.Serializable {

	private Integer id;
	private Unidadmedida unidadmedida;
	private Producto productoByCodigoproducto;
	private Producto productoByCodigoinsumo;
	private int carga;
	private float cantidadinsumo;

	public Ingrediente() {
	}

	public Ingrediente(Unidadmedida unidadmedida,
			Producto productoByCodigoproducto, Producto productoByCodigoinsumo,
			int carga, float cantidadinsumo) {
		this.unidadmedida = unidadmedida;
		this.productoByCodigoproducto = productoByCodigoproducto;
		this.productoByCodigoinsumo = productoByCodigoinsumo;
		this.carga = carga;
		this.cantidadinsumo = cantidadinsumo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOUNIDADMEDIDA", nullable = false)
	public Unidadmedida getUnidadmedida() {
		return this.unidadmedida;
	}

	public void setUnidadmedida(Unidadmedida unidadmedida) {
		this.unidadmedida = unidadmedida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOPRODUCTO", nullable = false)
	public Producto getProductoByCodigoproducto() {
		return this.productoByCodigoproducto;
	}

	public void setProductoByCodigoproducto(Producto productoByCodigoproducto) {
		this.productoByCodigoproducto = productoByCodigoproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOINSUMO", nullable = false)
	public Producto getProductoByCodigoinsumo() {
		return this.productoByCodigoinsumo;
	}

	public void setProductoByCodigoinsumo(Producto productoByCodigoinsumo) {
		this.productoByCodigoinsumo = productoByCodigoinsumo;
	}

	@Column(name = "CARGA", nullable = false)
	public int getCarga() {
		return this.carga;
	}

	public void setCarga(int carga) {
		this.carga = carga;
	}

	@Column(name = "CANTIDADINSUMO", nullable = false, precision = 12, scale = 0)
	public float getCantidadinsumo() {
		return this.cantidadinsumo;
	}

	public void setCantidadinsumo(float cantidadinsumo) {
		this.cantidadinsumo = cantidadinsumo;
	}

}
