package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Insumo generated by hbm2java
 */
@Entity
@Table(name = "insumo", catalog = "lapalmera")
public class Insumo implements java.io.Serializable {

	private String codigoinsumo;
	private String nombreinsumo;
	private String codigounidadmedida;
	private Integer stockcriticoinsumo;
	private Long consumo;
	private Long devolucion;
	private Long comprasinsumo;
	private Long traspasosinsumo;
	private Long saldoinsumo;
	private String observacion;

	public Insumo() {
	}

	public Insumo(String codigoinsumo, String codigounidadmedida) {
		this.codigoinsumo = codigoinsumo;
		this.codigounidadmedida = codigounidadmedida;
	}

	public Insumo(String codigoinsumo, String nombreinsumo,
			String codigounidadmedida, Integer stockcriticoinsumo,
			Long consumo, Long devolucion, Long comprasinsumo,
			Long traspasosinsumo, Long saldoinsumo, String observacion) {
		this.codigoinsumo = codigoinsumo;
		this.nombreinsumo = nombreinsumo;
		this.codigounidadmedida = codigounidadmedida;
		this.stockcriticoinsumo = stockcriticoinsumo;
		this.consumo = consumo;
		this.devolucion = devolucion;
		this.comprasinsumo = comprasinsumo;
		this.traspasosinsumo = traspasosinsumo;
		this.saldoinsumo = saldoinsumo;
		this.observacion = observacion;
	}

	@Id
	@Column(name = "CODIGOINSUMO", unique = true, nullable = false, length = 20)
	public String getCodigoinsumo() {
		return this.codigoinsumo;
	}

	public void setCodigoinsumo(String codigoinsumo) {
		this.codigoinsumo = codigoinsumo;
	}

	@Column(name = "NOMBREINSUMO", length = 80)
	public String getNombreinsumo() {
		return this.nombreinsumo;
	}

	public void setNombreinsumo(String nombreinsumo) {
		this.nombreinsumo = nombreinsumo;
	}

	@Column(name = "CODIGOUNIDADMEDIDA", nullable = false, length = 20)
	public String getCodigounidadmedida() {
		return this.codigounidadmedida;
	}

	public void setCodigounidadmedida(String codigounidadmedida) {
		this.codigounidadmedida = codigounidadmedida;
	}

	@Column(name = "STOCKCRITICOINSUMO")
	public Integer getStockcriticoinsumo() {
		return this.stockcriticoinsumo;
	}

	public void setStockcriticoinsumo(Integer stockcriticoinsumo) {
		this.stockcriticoinsumo = stockcriticoinsumo;
	}

	@Column(name = "CONSUMO", precision = 10, scale = 0)
	public Long getConsumo() {
		return this.consumo;
	}

	public void setConsumo(Long consumo) {
		this.consumo = consumo;
	}

	@Column(name = "DEVOLUCION", precision = 10, scale = 0)
	public Long getDevolucion() {
		return this.devolucion;
	}

	public void setDevolucion(Long devolucion) {
		this.devolucion = devolucion;
	}

	@Column(name = "COMPRASINSUMO", precision = 10, scale = 0)
	public Long getComprasinsumo() {
		return this.comprasinsumo;
	}

	public void setComprasinsumo(Long comprasinsumo) {
		this.comprasinsumo = comprasinsumo;
	}

	@Column(name = "TRASPASOSINSUMO", precision = 10, scale = 0)
	public Long getTraspasosinsumo() {
		return this.traspasosinsumo;
	}

	public void setTraspasosinsumo(Long traspasosinsumo) {
		this.traspasosinsumo = traspasosinsumo;
	}

	@Column(name = "SALDOINSUMO", precision = 10, scale = 0)
	public Long getSaldoinsumo() {
		return this.saldoinsumo;
	}

	public void setSaldoinsumo(Long saldoinsumo) {
		this.saldoinsumo = saldoinsumo;
	}

	@Column(name = "OBSERVACION", length = 80)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
