package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ordenfabricacion generated by hbm2java
 */
@Entity
@Table(name = "ordenfabricacion", catalog = "lapalmera")
public class Ordenfabricacion implements java.io.Serializable {

	private String codigoordenfabricacion;
	private Pedido pedido;
	private Producto producto;
	private Estadoordenfabricacion estadoordenfabricacion;
	private Date fechaingresoordenfabricacion;
	private int cantidadproducto;
	private Set<Entregainsumo> entregainsumos = new HashSet<Entregainsumo>(0);
	private Set<Programaproduccion> programaproduccions = new HashSet<Programaproduccion>(
			0);
	private Set<Devolucioninsumo> devolucioninsumos = new HashSet<Devolucioninsumo>(
			0);

	public Ordenfabricacion() {
	}

	public Ordenfabricacion(String codigoordenfabricacion, Pedido pedido,
			Producto producto, Estadoordenfabricacion estadoordenfabricacion,
			Date fechaingresoordenfabricacion, int cantidadproducto) {
		this.codigoordenfabricacion = codigoordenfabricacion;
		this.pedido = pedido;
		this.producto = producto;
		this.estadoordenfabricacion = estadoordenfabricacion;
		this.fechaingresoordenfabricacion = fechaingresoordenfabricacion;
		this.cantidadproducto = cantidadproducto;
	}

	public Ordenfabricacion(String codigoordenfabricacion, Pedido pedido,
			Producto producto, Estadoordenfabricacion estadoordenfabricacion,
			Date fechaingresoordenfabricacion, int cantidadproducto,
			Set<Entregainsumo> entregainsumos,
			Set<Programaproduccion> programaproduccions,
			Set<Devolucioninsumo> devolucioninsumos) {
		this.codigoordenfabricacion = codigoordenfabricacion;
		this.pedido = pedido;
		this.producto = producto;
		this.estadoordenfabricacion = estadoordenfabricacion;
		this.fechaingresoordenfabricacion = fechaingresoordenfabricacion;
		this.cantidadproducto = cantidadproducto;
		this.entregainsumos = entregainsumos;
		this.programaproduccions = programaproduccions;
		this.devolucioninsumos = devolucioninsumos;
	}

	@Id
	@Column(name = "CODIGOORDENFABRICACION", unique = true, nullable = false, length = 20)
	public String getCodigoordenfabricacion() {
		return this.codigoordenfabricacion;
	}

	public void setCodigoordenfabricacion(String codigoordenfabricacion) {
		this.codigoordenfabricacion = codigoordenfabricacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUMEROPEDIDO", nullable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOPRODUCTO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOESTADOORDENFABRICACION", nullable = false)
	public Estadoordenfabricacion getEstadoordenfabricacion() {
		return this.estadoordenfabricacion;
	}

	public void setEstadoordenfabricacion(
			Estadoordenfabricacion estadoordenfabricacion) {
		this.estadoordenfabricacion = estadoordenfabricacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAINGRESOORDENFABRICACION", nullable = false, length = 19)
	public Date getFechaingresoordenfabricacion() {
		return this.fechaingresoordenfabricacion;
	}

	public void setFechaingresoordenfabricacion(
			Date fechaingresoordenfabricacion) {
		this.fechaingresoordenfabricacion = fechaingresoordenfabricacion;
	}

	@Column(name = "CANTIDADPRODUCTO", nullable = false)
	public int getCantidadproducto() {
		return this.cantidadproducto;
	}

	public void setCantidadproducto(int cantidadproducto) {
		this.cantidadproducto = cantidadproducto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ordenfabricacion")
	public Set<Entregainsumo> getEntregainsumos() {
		return this.entregainsumos;
	}

	public void setEntregainsumos(Set<Entregainsumo> entregainsumos) {
		this.entregainsumos = entregainsumos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ordenfabricacion")
	public Set<Programaproduccion> getProgramaproduccions() {
		return this.programaproduccions;
	}

	public void setProgramaproduccions(
			Set<Programaproduccion> programaproduccions) {
		this.programaproduccions = programaproduccions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ordenfabricacion")
	public Set<Devolucioninsumo> getDevolucioninsumos() {
		return this.devolucioninsumos;
	}

	public void setDevolucioninsumos(Set<Devolucioninsumo> devolucioninsumos) {
		this.devolucioninsumos = devolucioninsumos;
	}

}
