package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Otracaracteristica generated by hbm2java
 */
@Entity
@Table(name = "otracaracteristica", catalog = "lapalmera")
public class Otracaracteristica implements java.io.Serializable {

	private String codigootracaracteristica;
	private String nombreotracaracteristica;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Otracaracteristica() {
	}

	public Otracaracteristica(String codigootracaracteristica) {
		this.codigootracaracteristica = codigootracaracteristica;
	}

	public Otracaracteristica(String codigootracaracteristica,
			String nombreotracaracteristica, Set<Producto> productos) {
		this.codigootracaracteristica = codigootracaracteristica;
		this.nombreotracaracteristica = nombreotracaracteristica;
		this.productos = productos;
	}

	@Id
	@Column(name = "CODIGOOTRACARACTERISTICA", unique = true, nullable = false, length = 20)
	public String getCodigootracaracteristica() {
		return this.codigootracaracteristica;
	}

	public void setCodigootracaracteristica(String codigootracaracteristica) {
		this.codigootracaracteristica = codigootracaracteristica;
	}

	@Column(name = "NOMBREOTRACARACTERISTICA", length = 80)
	public String getNombreotracaracteristica() {
		return this.nombreotracaracteristica;
	}

	public void setNombreotracaracteristica(String nombreotracaracteristica) {
		this.nombreotracaracteristica = nombreotracaracteristica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "otracaracteristica")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
