package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productolinea generated by hbm2java
 */
@Entity
@Table(name = "productolinea", catalog = "lapalmera")
public class Productolinea implements java.io.Serializable {

	private Integer id;
	private Producto producto;
	private Lineaproduccion lineaproduccion;
	private int prioridad;

	public Productolinea() {
	}

	public Productolinea(Producto producto, Lineaproduccion lineaproduccion,
			int prioridad) {
		this.producto = producto;
		this.lineaproduccion = lineaproduccion;
		this.prioridad = prioridad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOPRODUCTO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOLINEAPRODUCCION", nullable = false)
	public Lineaproduccion getLineaproduccion() {
		return this.lineaproduccion;
	}

	public void setLineaproduccion(Lineaproduccion lineaproduccion) {
		this.lineaproduccion = lineaproduccion;
	}

	@Column(name = "PRIORIDAD", nullable = false)
	public int getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(int prioridad) {
		this.prioridad = prioridad;
	}

}
