package cl.obam.pasteleria.lapalmera.model;

// Generated 09-09-2015 12:04:17 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductolineaId generated by hbm2java
 */
@Embeddable
public class ProductolineaId implements java.io.Serializable {

	private String codigoproducto;
	private String codigolineaproduccion;

	public ProductolineaId() {
	}

	public ProductolineaId(String codigoproducto, String codigolineaproduccion) {
		this.codigoproducto = codigoproducto;
		this.codigolineaproduccion = codigolineaproduccion;
	}

	@Column(name = "CODIGOPRODUCTO", nullable = false, length = 20)
	public String getCodigoproducto() {
		return this.codigoproducto;
	}

	public void setCodigoproducto(String codigoproducto) {
		this.codigoproducto = codigoproducto;
	}

	@Column(name = "CODIGOLINEAPRODUCCION", nullable = false, length = 20)
	public String getCodigolineaproduccion() {
		return this.codigolineaproduccion;
	}

	public void setCodigolineaproduccion(String codigolineaproduccion) {
		this.codigolineaproduccion = codigolineaproduccion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductolineaId))
			return false;
		ProductolineaId castOther = (ProductolineaId) other;

		return ((this.getCodigoproducto() == castOther.getCodigoproducto()) || (this
				.getCodigoproducto() != null
				&& castOther.getCodigoproducto() != null && this
				.getCodigoproducto().equals(castOther.getCodigoproducto())))
				&& ((this.getCodigolineaproduccion() == castOther
						.getCodigolineaproduccion()) || (this
						.getCodigolineaproduccion() != null
						&& castOther.getCodigolineaproduccion() != null && this
						.getCodigolineaproduccion().equals(
								castOther.getCodigolineaproduccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoproducto() == null ? 0 : this.getCodigoproducto()
						.hashCode());
		result = 37
				* result
				+ (getCodigolineaproduccion() == null ? 0 : this
						.getCodigolineaproduccion().hashCode());
		return result;
	}

}
