package cl.obam.pasteleria.lapalmera.model;

// Generated 14-08-2015 10:04:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UbicacionId generated by hbm2java
 */
@Embeddable
public class UbicacionId implements java.io.Serializable {

	private String codigoproducto;
	private String codigobodega;
	private Date fechaingreso;
	private Date horaingreso;
	private Date fechavencimiento;

	public UbicacionId() {
	}

	public UbicacionId(String codigoproducto, String codigobodega,
			Date fechaingreso, Date horaingreso, Date fechavencimiento) {
		this.codigoproducto = codigoproducto;
		this.codigobodega = codigobodega;
		this.fechaingreso = fechaingreso;
		this.horaingreso = horaingreso;
		this.fechavencimiento = fechavencimiento;
	}

	@Column(name = "CODIGOPRODUCTO", nullable = false, length = 20)
	public String getCodigoproducto() {
		return this.codigoproducto;
	}

	public void setCodigoproducto(String codigoproducto) {
		this.codigoproducto = codigoproducto;
	}

	@Column(name = "CODIGOBODEGA", nullable = false, length = 20)
	public String getCodigobodega() {
		return this.codigobodega;
	}

	public void setCodigobodega(String codigobodega) {
		this.codigobodega = codigobodega;
	}

	@Column(name = "FECHAINGRESO", nullable = false, length = 10)
	public Date getFechaingreso() {
		return this.fechaingreso;
	}

	public void setFechaingreso(Date fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

	@Column(name = "HORAINGRESO", nullable = false, length = 8)
	public Date getHoraingreso() {
		return this.horaingreso;
	}

	public void setHoraingreso(Date horaingreso) {
		this.horaingreso = horaingreso;
	}

	@Column(name = "FECHAVENCIMIENTO", nullable = false, length = 10)
	public Date getFechavencimiento() {
		return this.fechavencimiento;
	}

	public void setFechavencimiento(Date fechavencimiento) {
		this.fechavencimiento = fechavencimiento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UbicacionId))
			return false;
		UbicacionId castOther = (UbicacionId) other;

		return ((this.getCodigoproducto() == castOther.getCodigoproducto()) || (this
				.getCodigoproducto() != null
				&& castOther.getCodigoproducto() != null && this
				.getCodigoproducto().equals(castOther.getCodigoproducto())))
				&& ((this.getCodigobodega() == castOther.getCodigobodega()) || (this
						.getCodigobodega() != null
						&& castOther.getCodigobodega() != null && this
						.getCodigobodega().equals(castOther.getCodigobodega())))
				&& ((this.getFechaingreso() == castOther.getFechaingreso()) || (this
						.getFechaingreso() != null
						&& castOther.getFechaingreso() != null && this
						.getFechaingreso().equals(castOther.getFechaingreso())))
				&& ((this.getHoraingreso() == castOther.getHoraingreso()) || (this
						.getHoraingreso() != null
						&& castOther.getHoraingreso() != null && this
						.getHoraingreso().equals(castOther.getHoraingreso())))
				&& ((this.getFechavencimiento() == castOther
						.getFechavencimiento()) || (this.getFechavencimiento() != null
						&& castOther.getFechavencimiento() != null && this
						.getFechavencimiento().equals(
								castOther.getFechavencimiento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoproducto() == null ? 0 : this.getCodigoproducto()
						.hashCode());
		result = 37
				* result
				+ (getCodigobodega() == null ? 0 : this.getCodigobodega()
						.hashCode());
		result = 37
				* result
				+ (getFechaingreso() == null ? 0 : this.getFechaingreso()
						.hashCode());
		result = 37
				* result
				+ (getHoraingreso() == null ? 0 : this.getHoraingreso()
						.hashCode());
		result = 37
				* result
				+ (getFechavencimiento() == null ? 0 : this
						.getFechavencimiento().hashCode());
		return result;
	}

}
