package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ubicacion generated by hbm2java
 */
@Entity
@Table(name = "ubicacion", catalog = "lapalmera")
public class Ubicacion implements java.io.Serializable {

	private Integer id;
	private Unidadmedida unidadmedida;
	private Producto producto;
	private Bodega bodega;
	private Date fechaingreso;
	private Date fechavencimiento;
	private Float cantidad;
	private String observacionubicacion;

	public Ubicacion() {
	}

	public Ubicacion(Unidadmedida unidadmedida, Producto producto,
			Bodega bodega, Date fechaingreso, Date fechavencimiento,
			Float cantidad, String observacionubicacion) {
		this.unidadmedida = unidadmedida;
		this.producto = producto;
		this.bodega = bodega;
		this.fechaingreso = fechaingreso;
		this.fechavencimiento = fechavencimiento;
		this.cantidad = cantidad;
		this.observacionubicacion = observacionubicacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOUNIDADMEDIDA")
	public Unidadmedida getUnidadmedida() {
		return this.unidadmedida;
	}

	public void setUnidadmedida(Unidadmedida unidadmedida) {
		this.unidadmedida = unidadmedida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOPRODUCTO")
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOBODEGA")
	public Bodega getBodega() {
		return this.bodega;
	}

	public void setBodega(Bodega bodega) {
		this.bodega = bodega;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAINGRESO", length = 19)
	public Date getFechaingreso() {
		return this.fechaingreso;
	}

	public void setFechaingreso(Date fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHAVENCIMIENTO", length = 10)
	public Date getFechavencimiento() {
		return this.fechavencimiento;
	}

	public void setFechavencimiento(Date fechavencimiento) {
		this.fechavencimiento = fechavencimiento;
	}

	@Column(name = "CANTIDAD", precision = 12, scale = 0)
	public Float getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Float cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "OBSERVACIONUBICACION", length = 80)
	public String getObservacionubicacion() {
		return this.observacionubicacion;
	}

	public void setObservacionubicacion(String observacionubicacion) {
		this.observacionubicacion = observacionubicacion;
	}

}
