package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unidadmedida generated by hbm2java
 */
@Entity
@Table(name = "unidadmedida", catalog = "lapalmera")
public class Unidadmedida implements java.io.Serializable {

	private String codigo;
	private Familia familia;
	private String nombre;
	private Set<Producto> productos = new HashSet<Producto>(0);
	private Set<Detalleentregainsumo> detalleentregainsumos = new HashSet<Detalleentregainsumo>(
			0);
	private Set<Capturaproduccion> capturaproduccions = new HashSet<Capturaproduccion>(
			0);
	private Set<Ubicacion> ubicacions = new HashSet<Ubicacion>(0);
	private Set<Ingrediente> ingredientes = new HashSet<Ingrediente>(0);
	private Set<Stock> stocks = new HashSet<Stock>(0);

	public Unidadmedida() {
	}

	public Unidadmedida(String codigo, Familia familia) {
		this.codigo = codigo;
		this.familia = familia;
	}

	public Unidadmedida(String codigo, Familia familia, String nombre,
			Set<Producto> productos,
			Set<Detalleentregainsumo> detalleentregainsumos,
			Set<Capturaproduccion> capturaproduccions,
			Set<Ubicacion> ubicacions, Set<Ingrediente> ingredientes,
			Set<Stock> stocks) {
		this.codigo = codigo;
		this.familia = familia;
		this.nombre = nombre;
		this.productos = productos;
		this.detalleentregainsumos = detalleentregainsumos;
		this.capturaproduccions = capturaproduccions;
		this.ubicacions = ubicacions;
		this.ingredientes = ingredientes;
		this.stocks = stocks;
	}

	@Id
	@Column(name = "CODIGO", unique = true, nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOFAMILIA", nullable = false)
	public Familia getFamilia() {
		return this.familia;
	}

	public void setFamilia(Familia familia) {
		this.familia = familia;
	}

	@Column(name = "NOMBRE", length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadmedida")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadmedida")
	public Set<Detalleentregainsumo> getDetalleentregainsumos() {
		return this.detalleentregainsumos;
	}

	public void setDetalleentregainsumos(
			Set<Detalleentregainsumo> detalleentregainsumos) {
		this.detalleentregainsumos = detalleentregainsumos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadmedida")
	public Set<Capturaproduccion> getCapturaproduccions() {
		return this.capturaproduccions;
	}

	public void setCapturaproduccions(Set<Capturaproduccion> capturaproduccions) {
		this.capturaproduccions = capturaproduccions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadmedida")
	public Set<Ubicacion> getUbicacions() {
		return this.ubicacions;
	}

	public void setUbicacions(Set<Ubicacion> ubicacions) {
		this.ubicacions = ubicacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadmedida")
	public Set<Ingrediente> getIngredientes() {
		return this.ingredientes;
	}

	public void setIngredientes(Set<Ingrediente> ingredientes) {
		this.ingredientes = ingredientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadmedida")
	public Set<Stock> getStocks() {
		return this.stocks;
	}

	public void setStocks(Set<Stock> stocks) {
		this.stocks = stocks;
	}

}
