package cl.obam.pasteleria.lapalmera.model;

// Generated 07-01-2016 12:33:38 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "lapalmera")
public class Usuario implements java.io.Serializable {

	private String loginusuario;
	private Grupo grupo;
	private Funcionario funcionario;
	private String passwordusuario;

	public Usuario() {
	}

	public Usuario(String loginusuario, Funcionario funcionario) {
		this.loginusuario = loginusuario;
		this.funcionario = funcionario;
	}

	public Usuario(String loginusuario, Grupo grupo, Funcionario funcionario,
			String passwordusuario) {
		this.loginusuario = loginusuario;
		this.grupo = grupo;
		this.funcionario = funcionario;
		this.passwordusuario = passwordusuario;
	}

	@Id
	@Column(name = "LOGINUSUARIO", unique = true, nullable = false, length = 20)
	public String getLoginusuario() {
		return this.loginusuario;
	}

	public void setLoginusuario(String loginusuario) {
		this.loginusuario = loginusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGOGRUPO")
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RUTFUNCIONARIO", nullable = false)
	public Funcionario getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(Funcionario funcionario) {
		this.funcionario = funcionario;
	}

	@Column(name = "PASSWORDUSUARIO", length = 50)
	public String getPasswordusuario() {
		return this.passwordusuario;
	}

	public void setPasswordusuario(String passwordusuario) {
		this.passwordusuario = passwordusuario;
	}

}
